### ISSUE TITLE
Haunted tests suite doesn't run

### ISSUE THREAD

**Issue by loganvolkers** [saasquatch/universal-hooks#4]
The universal hooks tests don't run the haunted tests. This is because Jest will set the implementation to React in the `describe` call and then it remains sticky.

This has also highlighted some possible failures in the Haunted testing library, as changing the dependency does not fix the haunted tests.

Here's what the code should do (notice the `beforeAll` instead of just calling code)

```js
  beforeAll(() => {
    setImplementation(React);
    setTestImplementation(ReactTestLib);
  });
  runTests();
  afterAll(()=>{
    setImplementation(null);
    setTestImplementation(null);
  })
```

**Comment by malcolmseyd** [comment]
This was fixed in commit b75d09e
